#!/bin/bash

# This script is used to generate cscope and ctags index files. If you do not
# use either of these tools, you can ignore this script.

source config.sh

MakeCScopeIndex()
{
    # Enumerate and save the path to each file cscope will parse.
    find $DS_PROJECT_PATH \
        -regextype posix-extended -regex ".*\.(c|cc|cpp|h)" \
        -type f \
        -print > cscope.files

    # -b Build cross-reference only.
    # -q Enable fast symbol lookup via an inverted index.
    # -k Don't index the C standard library.
    cscope -b -q -k
}

MakeCTags()
{
    # Speed ctags DB build up by handing ctags the cscope.files generated by
    # MakeCScopeIndex().
    ctags -L cscope.files
}

InstallIndices()
{
    # Move indices to the root of the project.
    mv cscope.in.out cscope.out cscope.po.out $DS_PROJECT_PATH
    mv tags $DS_PROJECT_PATH
}

Main()
{
    # Verify cscope is installed.
    if ! command -v cscope --help &> /dev/null
    then
        echo "${LRED}error cscope is not installed${NC}"
        exit 1
    fi

    # Verify ctags is installed.
    if ! command -v ctags --help &> /dev/null
    then
        echo "${LRED}error 'ctags' is not installed${NC}"
        exit 1
    fi

    MakeCScopeIndex
    MakeCTags
    InstallIndices

    # Cleanup, we don't need to keep the cscope.files around.
    rm cscope.files
}

Main
